/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FetchesApiFetchesChuckFetchImport } from './routes/fetches/apiFetches/chuckFetch'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const AppLazyImport = createFileRoute('/App')()
const IndexLazyImport = createFileRoute('/')()
const FetchesFetchLazyImport = createFileRoute('/fetches/fetch')()
const FetchesApiFetchesPokeFetchLazyImport = createFileRoute(
  '/fetches/apiFetches/pokeFetch',
)()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const AppLazyRoute = AppLazyImport.update({
  path: '/App',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/App.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const FetchesFetchLazyRoute = FetchesFetchLazyImport.update({
  path: '/fetches/fetch',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/fetches/fetch.lazy').then((d) => d.Route))

const FetchesApiFetchesPokeFetchLazyRoute =
  FetchesApiFetchesPokeFetchLazyImport.update({
    path: '/fetches/apiFetches/pokeFetch',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/fetches/apiFetches/pokeFetch.lazy').then((d) => d.Route),
  )

const FetchesApiFetchesChuckFetchRoute =
  FetchesApiFetchesChuckFetchImport.update({
    path: '/fetches/apiFetches/chuckFetch',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/App': {
      id: '/App'
      path: '/App'
      fullPath: '/App'
      preLoaderRoute: typeof AppLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/fetches/fetch': {
      id: '/fetches/fetch'
      path: '/fetches/fetch'
      fullPath: '/fetches/fetch'
      preLoaderRoute: typeof FetchesFetchLazyImport
      parentRoute: typeof rootRoute
    }
    '/fetches/apiFetches/chuckFetch': {
      id: '/fetches/apiFetches/chuckFetch'
      path: '/fetches/apiFetches/chuckFetch'
      fullPath: '/fetches/apiFetches/chuckFetch'
      preLoaderRoute: typeof FetchesApiFetchesChuckFetchImport
      parentRoute: typeof rootRoute
    }
    '/fetches/apiFetches/pokeFetch': {
      id: '/fetches/apiFetches/pokeFetch'
      path: '/fetches/apiFetches/pokeFetch'
      fullPath: '/fetches/apiFetches/pokeFetch'
      preLoaderRoute: typeof FetchesApiFetchesPokeFetchLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/App': typeof AppLazyRoute
  '/about': typeof AboutLazyRoute
  '/fetches/fetch': typeof FetchesFetchLazyRoute
  '/fetches/apiFetches/chuckFetch': typeof FetchesApiFetchesChuckFetchRoute
  '/fetches/apiFetches/pokeFetch': typeof FetchesApiFetchesPokeFetchLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/App': typeof AppLazyRoute
  '/about': typeof AboutLazyRoute
  '/fetches/fetch': typeof FetchesFetchLazyRoute
  '/fetches/apiFetches/chuckFetch': typeof FetchesApiFetchesChuckFetchRoute
  '/fetches/apiFetches/pokeFetch': typeof FetchesApiFetchesPokeFetchLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/App': typeof AppLazyRoute
  '/about': typeof AboutLazyRoute
  '/fetches/fetch': typeof FetchesFetchLazyRoute
  '/fetches/apiFetches/chuckFetch': typeof FetchesApiFetchesChuckFetchRoute
  '/fetches/apiFetches/pokeFetch': typeof FetchesApiFetchesPokeFetchLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/App'
    | '/about'
    | '/fetches/fetch'
    | '/fetches/apiFetches/chuckFetch'
    | '/fetches/apiFetches/pokeFetch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/App'
    | '/about'
    | '/fetches/fetch'
    | '/fetches/apiFetches/chuckFetch'
    | '/fetches/apiFetches/pokeFetch'
  id:
    | '__root__'
    | '/'
    | '/App'
    | '/about'
    | '/fetches/fetch'
    | '/fetches/apiFetches/chuckFetch'
    | '/fetches/apiFetches/pokeFetch'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AppLazyRoute: typeof AppLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  FetchesFetchLazyRoute: typeof FetchesFetchLazyRoute
  FetchesApiFetchesChuckFetchRoute: typeof FetchesApiFetchesChuckFetchRoute
  FetchesApiFetchesPokeFetchLazyRoute: typeof FetchesApiFetchesPokeFetchLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AppLazyRoute: AppLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  FetchesFetchLazyRoute: FetchesFetchLazyRoute,
  FetchesApiFetchesChuckFetchRoute: FetchesApiFetchesChuckFetchRoute,
  FetchesApiFetchesPokeFetchLazyRoute: FetchesApiFetchesPokeFetchLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/App",
        "/about",
        "/fetches/fetch",
        "/fetches/apiFetches/chuckFetch",
        "/fetches/apiFetches/pokeFetch"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/App": {
      "filePath": "App.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/fetches/fetch": {
      "filePath": "fetches/fetch.lazy.tsx"
    },
    "/fetches/apiFetches/chuckFetch": {
      "filePath": "fetches/apiFetches/chuckFetch.tsx"
    },
    "/fetches/apiFetches/pokeFetch": {
      "filePath": "fetches/apiFetches/pokeFetch.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
